name: Check Paths

on:
  push:
  pull_request:

jobs:
  checkpaths:
    name: Check Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check templates.json
        run: pwsh ci/CheckInvalidTemplatePaths.ps1 templates.json
